"""Update your_table structure

Revision ID: 84b9b887061c
Revises: b6028fa93ebc
Create Date: 2024-11-29 23:17:09.360522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84b9b887061c'
down_revision = 'b6028fa93ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_ibfk_1', 'books', type_='foreignkey')
    op.drop_column('books', 'user_id')
    op.drop_column('books', 'title')
    op.add_column('users', sa.Column('access_token', sa.String(length=512), nullable=False))
    op.add_column('users', sa.Column('access_token_expiry', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('refresh_token', sa.String(length=512), nullable=False))
    op.add_column('users', sa.Column('user_name', sa.String(length=512), nullable=False))
    op.drop_column('users', 'uuid')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('users', sa.Column('uuid', mysql.CHAR(length=32), nullable=False))
    op.drop_column('users', 'user_name')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'id')
    op.drop_column('users', 'access_token_expiry')
    op.drop_column('users', 'access_token')
    op.add_column('books', sa.Column('title', mysql.VARCHAR(length=256), nullable=False))
    op.add_column('books', sa.Column('user_id', mysql.CHAR(length=32), nullable=True))
    op.create_foreign_key('books_ibfk_1', 'books', 'users', ['user_id'], ['uuid'])
    # ### end Alembic commands ###
