"""Update session_authentications

Revision ID: aac3e21ef850
Revises: 42b5503e6e09
Create Date: 2024-11-30 00:07:15.184647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac3e21ef850'
down_revision = '42b5503e6e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_authentications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_authentications_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_authentications_id')
    )
    op.create_index(op.f('ix_session_authentications_id'), 'session_authentications', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_session_authentications_id'), table_name='session_authentications')
    op.drop_table('session_authentications')
    # ### end Alembic commands ###
